version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo_container
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: springboot_app
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo:27017/access_control
    restart: always

volumes:
  mongo_data:
